

export const sample_foods: any[] = [
  {
    id: 1,
    name: 'Sushi Roll',
    price: 15,
    tags: ['Asian', 'Seafood'],
    favorite: true,
    stars: 4.5,
    imageUrl: "assets/sushi-roll.jpg",
    origins: ["Japan"],
    cookTime: "15-25",
  },
  {
    id: 2,
    name: 'Chicken Curry',
    price: 12,
    tags: ['Asian', 'Spicy'],
    favorite: false,
    stars: 5,
    imageUrl: "assets/chicken-curry.jpg", 
    origins: ["India"],
    cookTime: "20-30",
  },
  {
    id: 3,
    name: 'Beef Burger',
    price: 8,
    tags: ['FastFood', 'American'],
    favorite: true,
    stars: 4,
    imageUrl: "assets/beef burger.jpg",
    origins: ["USA"],
    cookTime: "10-15",
  },
  {
    id: 4,
    name: 'Pad Thai',
    price: 11,
    tags: ['Asian', 'Noodles'],
    favorite: false,
    stars: 4.5,
    imageUrl: "assets/pad thai.jpeg",
    origins: ["Thailand"],
    cookTime: "15-20",
  },
  {
    id: 5,
    name: 'Caesar Salad',
    price: 7,
    tags: ['Healthy', 'Salad'],
    favorite: false,
    stars: 3.5,
    imageUrl: "assets/Caesar Salad.webp",
    origins: ["Mexico"],
    cookTime: "5-10",
  },
  {
    id: 6,
    name: 'Pasta Carbonara',
    price: 13,
    tags: ['Italian', 'Pasta'],
    favorite: true,
    stars: 5,
    imageUrl: "assets/pasta carbonara.jpg",
    origins: ["Italy"],
    cookTime: "15-20",
  },
  {
    id: 7,
    name: 'Margherita Pizza',
    price: 14,
    tags: ['Italian', 'Pizza'],
    favorite: false,
    stars: 4.5,
    imageUrl: "assets/Margherita-Pizza.jpg",
    origins: ["Italy"],
    cookTime: "15-20",
  },
  {
    id: 8,
    name: 'Fish and Chips',
    price: 10,
    tags: ['FastFood', 'Seafood'],
    favorite: false,
    stars: 4,
    imageUrl: "assets/fish-and-chips.jpeg",
    origins: ["United Kingdom"],
    cookTime: "15-20",
  },
  {
    id: 9,
    name: 'Classic Hamburger',
    tags: ['FastFood', 'American'],
    price: 9,
    favorite: true,
    stars: 4,
    imageUrl: "assets/classic-hamberg.jpeg",
    origins: ["USA"],
    cookTime: "10-15",
  },
  {
    id: 10,
    name: 'Pepperoni Pizza',
    price: 15,
    tags: ['Italian', 'Pizza'],
    favorite: true,
    stars: 4.5,
    imageUrl: "assets/pep-pizza.jpeg",
    origins: ["Italy"],
    cookTime: "15-20",
  }
]

export const sample_tags: any[] = [
  { name: 'All', count: 10 },
  { name: 'FastFood', count: 3 },
  { name: 'Pizza', count: 2 },
  { name: 'Italian', count: 3 },
  { name: 'Asian', count: 3 },
  { name: 'American', count: 2 },
  { name: 'Seafood', count: 2 },
  { name: 'Healthy', count: 1 }
]

export const sample_users: any[] = [
  {
    name: "John Doe",
    email: "vishalm@liftoffllc.com",
    password: "12345",
    address: "123 Main St, Anytown, USA",
    isAdmin: true,
  }, 
  {
    name: "John Doe 1",
    email: "vishalm+1@liftoffllc.com",
    password: "12345",
    address: "123 Main St, Anytown, USA",
    isAdmin: false,
  }
]