import { Food } from "./app/shared/models/food";

export const sample_foods: Food[] = [
  {
    id: 1,
    name: 'Sushi Roll',
    price: 15,
    tags: ['Japanese', 'Seafood', 'Dinner'],
    favorite: true,
    stars: 4.5,
    imageUrl: "assets/sushi-roll.jpg",
    origins: ["Japan"],
    cookTime: "15-25",
  },
  {
    id: 2,
    name: 'Chicken Curry',
    price: 12,
    tags: ['Indian', 'Spicy', 'Lunch'],
    favorite: false,
    stars: 5,
    imageUrl: "assets/chicken-curry.jpg", 
    origins: ["India"],
    cookTime: "20-30",
  },
  {
    id: 3,
    name: 'Beef Burger',
    price: 8,
    tags: ['FastFood', 'Burger', 'American'],
    favorite: true,
    stars: 4,
    imageUrl: "assets/beef burger.jpg",
    origins: ["USA"],
    cookTime: "10-15",
  },
  {
    id: 4,
    name: 'Pad Thai',
    price: 11,
    tags: ['Thai', 'Noodles', 'Dinner'],
    favorite: false,
    stars: 4.5,
    imageUrl: "assets/pad thai.jpeg",
    origins: ["Thailand"],
    cookTime: "15-20",
  },
  {
    id: 5,
    name: 'Caesar Salad',
    price: 7,
    tags: ['Healthy', 'Salad', 'Lunch'],
    favorite: false,
    stars: 3.5,
    imageUrl: "assets/Caesar Salad.webp",
    origins: ["Mexico"],
    cookTime: "5-10",
  },
  {
    id: 6,
    name: 'Pasta Carbonara',
    price: 13,
    tags: ['Italian', 'Pasta', 'Dinner'],
    favorite: true,
    stars: 5,
    imageUrl: "assets/pasta carbonara.jpg",
    origins: ["Italy"],
    cookTime: "15-20",
  }
]